### ISSUE TITLE
add github workflow for pytest

### ISSUE THREAD

**Issue by kcpevey** [kcpevey/client_cookiecutter#2]
github workflow for pytest:
```
name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@master
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          activate-environment: env_name
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          channels: conda-forge
          channel-priority: strict

      - name: Install package
        run: |
          pip install -e .
      - name: Conda list
        run: conda list

      - name: Create properties file
        run: cat properties.tpl > ~/.properties

      - name: Test with pytest
        run: |
          pytest tests -vvv -m "not local_required" --cov=package_name
```
