### ISSUE TITLE
add github workflow for linting

### ISSUE THREAD

**Issue by kcpevey** [kcpevey/client_cookiecutter#3]
```
name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pre-commit
        run: |
          pip install pre-commit jupyter pygments==2.10.0 markupsafe==2.0.1
      - name: Run pre-commit hooks
        run: pre-commit run --all
```

pre-commit file:
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-added-large-files
    - id: trailing-whitespace
    - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
    - id: isort
      args: ["--profile", "black"]
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace

exclude: CHANGELOG.rst
```
